### ISSUE TITLE
About English-centric

### ISSUE THREAD

**Issue by ohkimchi** [mvolkmann/web-translate#2]
I want to confirm about this, if I have a web page which is displaying Thai words, will this library help to translate the content to English?

**Comment by mvolkmann** [comment]
It is not meant to translate dynamic text. For example, it can generate translations at build time for labels in a user interface like “Phone Number” and then display those translations at runtime. It can also do runtime translations such as translating text that is obtained from a REST call, but that can get expensive because then the translations are performed for every session of every user. You would have to pay a fee to either Yandex or Google Translate to do that.

Let me know if I didn’t fully answer your question.

**Comment by rohitm94** [comment]
I have a React application which has landing page with English vocabulary. Can this library help converting the content into spanish on selection of language from dropdown on the page ?

Also, can a more detailed examples be given with whole code structure?

**Comment by mvolkmann** [comment]
Sorry I didn't reply earlier. I may have expanded the README after you asked this question. I'm really hoping that it provides enough detail.
